# infrastructure/kyverno/policies/kustomization.yaml
# Security policies for cluster-wide enforcement
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - disallow-privileged.yaml
  - require-resource-limits.yaml
  - require-labels.yaml
  - require-non-root.yaml
  - disallow-latest-tag.yaml
  - add-default-securitycontext.yaml
