# infrastructure/networking/kustomization.yaml
# Networking stack: Istio ingress, DNS, Network Policies
# TODO: Add Istio Gateway, VirtualService templates
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

resources: []
# Future additions:
# - gateway.yaml
# - default-network-policies.yaml
